name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
